#data_new$feature_45 <- as.character(data_new$feature_45)
data_new$feature_20 <- as.character(data_new$feature_20)
data_new$feature_21 <- as.character(data_new$feature_21)
data_new$feature_22 <- as.character(data_new$feature_22)
data_new$feature_24 <- as.character(data_new$feature_24)
data_new$feature_38 <- as.character(data_new$feature_38)
data_new$feature_77 <- as.character(data_new$feature_77)





data_new$customer_no <- as.factor(data_new$customer_no)
data_new$feature_4 <- as.factor(data_new$feature_4)
#data_new$feature_6 <- as.factor(data_new$feature_6)
data_new$feature_14 <- as.factor(data_new$feature_14)
data_new$feature_19 <- as.factor(data_new$feature_19)
data_new$feature_25 <- as.factor(data_new$feature_25)
data_new$feature_26 <- as.factor(data_new$feature_26)
data_new$feature_29 <- as.factor(data_new$feature_29)
data_new$feature_30 <- as.factor(data_new$feature_30)
data_new$feature_31 <- as.factor(data_new$feature_31)
data_new$feature_34 <- as.factor(data_new$feature_34)
data_new$feature_39 <- as.factor(data_new$feature_39)
data_new$feature_40 <- as.factor(data_new$feature_40)
data_new$feature_41 <- as.factor(data_new$feature_41)
data_new$feature_42 <- as.factor(data_new$feature_42)
data_new$feature_44 <- as.factor(data_new$feature_44)
#data_new$feature_49 <- as.factor(data_new$feature_49)
data_new$feature_52 <- as.numeric(data_new$feature_52)
data_new$feature_55 <- as.factor(data_new$feature_55)
data_new$feature_56 <- as.factor(data_new$feature_56)
data_new$feature_64 <- as.factor(data_new$feature_64)
data_new$feature_65 <- as.factor(data_new$feature_65)
data_new$feature_66 <- as.factor(data_new$feature_66)
data_new$feature_67 <- as.factor(data_new$feature_67)
data_new$feature_68 <- as.factor(data_new$feature_68)
data_new$feature_71 <- as.factor(data_new$feature_71)
#data_new$feature_74 <- as.factor(data_new$feature_74)
data_new$feature_76 <- as.factor(data_new$feature_76)
data_new$feature_78 <- as.factor(data_new$feature_78)
#data_new$feature_5 <- as.factor(data_new$feature_5)
data_new$feature_8 <- as.factor(data_new$feature_8)
data_new$feature_9 <- as.factor(data_new$feature_9)
data_new$feature_10 <- as.factor(data_new$feature_10)
data_new$feature_11 <- as.factor(data_new$feature_11)
data_new$feature_12 <- as.factor(data_new$feature_12)
data_new$feature_13 <- as.factor(data_new$feature_13)
data_new$feature_15 <- as.factor(data_new$feature_15)
data_new$feature_16 <- as.factor(data_new$feature_16)
data_new$feature_17 <- as.factor(data_new$feature_17)
data_new$feature_18 <- as.factor(data_new$feature_18)
data_new$feature_20 <- as.factor(data_new$feature_20)
data_new$feature_21 <- as.factor(data_new$feature_21)
data_new$feature_22 <- as.factor(data_new$feature_22)
data_new$feature_23 <- as.factor(data_new$feature_23)
data_new$feature_24 <- as.factor(data_new$feature_24)
data_new$feature_27 <- as.factor(data_new$feature_27)
data_new$feature_28 <- as.factor(data_new$feature_28)
data_new$feature_32 <- as.factor(data_new$feature_32)
data_new$feature_33 <- as.factor(data_new$feature_33)
data_new$feature_36 <- as.factor(data_new$feature_36)
data_new$feature_37 <- as.factor(data_new$feature_37)
data_new$feature_38 <- as.factor(data_new$feature_38)
data_new$feature_46 <- as.factor(data_new$feature_46)
data_new$feature_47 <- as.factor(data_new$feature_47)
data_new$feature_48 <- as.factor(data_new$feature_48)
data_new$feature_50 <- as.factor(data_new$feature_50)
data_new$feature_51 <- as.factor(data_new$feature_51)
data_new$feature_53 <- as.factor(data_new$feature_53)
data_new$feature_57 <- as.factor(data_new$feature_57)
data_new$feature_58 <- as.factor(data_new$feature_58)
data_new$feature_59 <- as.factor(data_new$feature_59)
data_new$feature_60 <- as.factor(data_new$feature_60)
data_new$feature_61 <- as.factor(data_new$feature_61)
data_new$feature_62 <- as.factor(data_new$feature_62)
data_new$feature_63 <- as.factor(data_new$feature_63)
data_new$feature_70 <- as.factor(data_new$feature_70)
data_new$feature_72 <- as.factor(data_new$feature_72)
data_new$feature_73 <- as.factor(data_new$feature_73)
data_new$feature_75 <- as.factor(data_new$feature_75)
data_new$feature_77 <- as.factor(data_new$feature_77)
data_new$feature_79 <- as.factor(data_new$feature_79)
data_new$mean_diff_open_enquiry_dt <- as.numeric(data_new$mean_diff_open_enquiry_dt)
data_new$mean_diff_lastpayment_opened_dt <- as.numeric(data_new$mean_diff_lastpayment_opened_dt)

data_new$feature_5 <- NULL
data_new$feature_6 <- NULL
data_new$feature_43 <- NULL
data_new$ feature_45 <- NULL

##############################################

data_new_test$feature_20 <- as.character(data_new_test$feature_20)
data_new_test$feature_21 <- as.character(data_new_test$feature_21)
data_new_test$feature_22 <- as.character(data_new_test$feature_22)
data_new_test$feature_24 <- as.character(data_new_test$feature_24)
data_new_test$feature_38 <- as.character(data_new_test$feature_38)
data_new_test$feature_77 <- as.character(data_new_test$feature_77)





data_new_test$customer_no <- as.factor(data_new_test$customer_no)
data_new_test$feature_4 <- as.factor(data_new_test$feature_4)
#data_new_test$feature_6 <- as.factor(data_new_test$feature_6)
data_new_test$feature_14 <- as.factor(data_new_test$feature_14)
data_new_test$feature_19 <- as.factor(data_new_test$feature_19)
data_new_test$feature_25 <- as.factor(data_new_test$feature_25)
data_new_test$feature_26 <- as.factor(data_new_test$feature_26)
data_new_test$feature_29 <- as.factor(data_new_test$feature_29)
data_new_test$feature_30 <- as.factor(data_new_test$feature_30)
data_new_test$feature_31 <- as.factor(data_new_test$feature_31)
data_new_test$feature_34 <- as.factor(data_new_test$feature_34)
data_new_test$feature_39 <- as.factor(data_new_test$feature_39)
data_new_test$feature_40 <- as.factor(data_new_test$feature_40)
data_new_test$feature_41 <- as.factor(data_new_test$feature_41)
data_new_test$feature_42 <- as.factor(data_new_test$feature_42)
data_new_test$feature_44 <- as.factor(data_new_test$feature_44)
#data_new_test$feature_49 <- as.factor(data_new_test$feature_49)
data_new_test$feature_52 <- as.numeric(data_new_test$feature_52)
data_new_test$feature_55 <- as.factor(data_new_test$feature_55)
data_new_test$feature_56 <- as.factor(data_new_test$feature_56)
data_new_test$feature_64 <- as.factor(data_new_test$feature_64)
data_new_test$feature_65 <- as.factor(data_new_test$feature_65)
data_new_test$feature_66 <- as.factor(data_new_test$feature_66)
data_new_test$feature_67 <- as.factor(data_new_test$feature_67)
data_new_test$feature_68 <- as.factor(data_new_test$feature_68)
data_new_test$feature_71 <- as.factor(data_new_test$feature_71)
#data_new_test$feature_74 <- as.factor(data_new_test$feature_74)
data_new_test$feature_76 <- as.factor(data_new_test$feature_76)
data_new_test$feature_78 <- as.factor(data_new_test$feature_78)
#data_new_test$feature_5 <- as.factor(data_new_test$feature_5)
data_new_test$feature_8 <- as.factor(data_new_test$feature_8)
data_new_test$feature_9 <- as.factor(data_new_test$feature_9)
data_new_test$feature_10 <- as.factor(data_new_test$feature_10)
data_new_test$feature_11 <- as.factor(data_new_test$feature_11)
data_new_test$feature_12 <- as.factor(data_new_test$feature_12)
data_new_test$feature_13 <- as.factor(data_new_test$feature_13)
data_new_test$feature_15 <- as.factor(data_new_test$feature_15)
data_new_test$feature_16 <- as.factor(data_new_test$feature_16)
data_new_test$feature_17 <- as.factor(data_new_test$feature_17)
data_new_test$feature_18 <- as.factor(data_new_test$feature_18)
data_new_test$feature_20 <- as.factor(data_new_test$feature_20)
data_new_test$feature_21 <- as.factor(data_new_test$feature_21)
data_new_test$feature_22 <- as.factor(data_new_test$feature_22)
data_new_test$feature_23 <- as.factor(data_new_test$feature_23)
data_new_test$feature_24 <- as.factor(data_new_test$feature_24)
data_new_test$feature_27 <- as.factor(data_new_test$feature_27)
data_new_test$feature_28 <- as.factor(data_new_test$feature_28)
data_new_test$feature_32 <- as.factor(data_new_test$feature_32)
data_new_test$feature_33 <- as.factor(data_new_test$feature_33)
data_new_test$feature_36 <- as.factor(data_new_test$feature_36)
data_new_test$feature_37 <- as.factor(data_new_test$feature_37)
data_new_test$feature_38 <- as.factor(data_new_test$feature_38)
data_new_test$feature_46 <- as.factor(data_new_test$feature_46)
data_new_test$feature_47 <- as.factor(data_new_test$feature_47)
data_new_test$feature_48 <- as.factor(data_new_test$feature_48)
data_new_test$feature_50 <- as.factor(data_new_test$feature_50)
data_new_test$feature_51 <- as.factor(data_new_test$feature_51)
data_new_test$feature_53 <- as.factor(data_new_test$feature_53)
data_new_test$feature_57 <- as.factor(data_new_test$feature_57)
data_new_test$feature_58 <- as.factor(data_new_test$feature_58)
data_new_test$feature_59 <- as.factor(data_new_test$feature_59)
data_new_test$feature_60 <- as.factor(data_new_test$feature_60)
data_new_test$feature_61 <- as.factor(data_new_test$feature_61)
data_new_test$feature_62 <- as.factor(data_new_test$feature_62)
data_new_test$feature_63 <- as.factor(data_new_test$feature_63)
data_new_test$feature_70 <- as.factor(data_new_test$feature_70)
data_new_test$feature_72 <- as.factor(data_new_test$feature_72)
data_new_test$feature_73 <- as.factor(data_new_test$feature_73)
data_new_test$feature_75 <- as.factor(data_new_test$feature_75)
data_new_test$feature_77 <- as.factor(data_new_test$feature_77)
data_new_test$feature_79 <- as.factor(data_new_test$feature_79)
data_new_test$mean_diff_open_enquiry_dt <- as.numeric(data_new_test$mean_diff_open_enquiry_dt)
data_new_test$mean_diff_lastpayment_opened_dt <- as.numeric(data_new_test$mean_diff_lastpayment_opened_dt)

data_new_test$feature_5 <- NULL
data_new_test$feature_6 <- NULL
data_new_test$feature_43 <- NULL
data_new_test$ feature_45 <- NULL

